name: Deploy Versioned MkDocs to GitHub Pages
permissions:
  contents: write    # for git pushes
  pages: write       # if you’re using the newer Pages API
on:
  push:
    tags:
      - 'v*'   # only deploy when you push a Git tag like v1.0, v2.0
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed to see tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mike

      - name: Generate Docs
        run: |
          python docs/generate_docs.py

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Dump $VERSION and list existing versions
        run: |
          echo "GITHUB_REF = $GITHUB_REF"
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Derived VERSION = '$VERSION'"
          # show all versions & aliases that Mike knows about
          mike list \
            --branch gh-pages \
            --deploy-prefix version

      - name: Deploy docs with mike
        env:
          # this token is provided automatically by Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          set -euxo pipefail
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Deploying docs for version $VERSION …"
          VERSION=${GITHUB_REF#refs/tags/}
          mike deploy --push --update-aliases "$VERSION" latest
          mike set-default latest --push --allow-undefined